# database generated on 2022-05-03 06:17 GMT
!!omap
- /home/riscv/RRF/Reports/2022-05-03_11:47:39.698641/fclass/tests/fclass_b1-01.S:
    commit_id: '-'
    isa:
    - RV32IF
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*F.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fclass_b1
