# database generated on 2022-05-03 07:04 GMT
!!omap
- /home/riscv/RRF/Reports/2022-05-03_12:33:59.495877/fclass/fclass/fcvt.d.l/tests/fcvt.d.l_b25-01.S:
    commit_id: '-'
    isa:
    - RV64IFD
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*F.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fcvt.d.l_b25
- /home/riscv/RRF/Reports/2022-05-03_12:33:59.495877/fclass/fclass/fcvt.d.l/tests/fcvt.d.l_b26-01.S:
    commit_id: '-'
    isa:
    - RV64IFD
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*F.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fcvt.d.l_b26
