# database generated on 2022-05-03 07:44 GMT
!!omap
- /home/riscv/RRF/Reports/2022-05-03_13:14:14.044280/rv64d_fclass/tests/fclass_b1-01.S:
    commit_id: '-'
    isa:
    - RV64IFD
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*F.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fclass_b1
