# database generated on 2022-05-03 07:15 GMT
!!omap
- /home/riscv/RRF/Reports/2022-05-03_12:45:36.966159/rv32f_fclass/tests/fclass_b1-01.S:
    commit_id: '-'
    isa:
    - RV32IF
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*F.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fclass_b1
